[package]
name = "nss-sys"
version = "0.1.0"
authors = ["Edouard Oger <eoger@fastmail.com>"]
edition = "2018"

[dependencies]
libloading = "0.5"
lazy_static = "1.3.0"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[features]
use_geckoview_nss = []
default = []
